version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8501:8501"
    volumes:
      - /database:/app/database
  scheduller:
    build: ./scheduller
    volumes:
      - /database:/app/database


